import { Language } from '../../i18n/settings';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Gatsby',
};

export default function RootLayout({
    children,
    params,
}: {
    // eslint-disable-next-line no-undef
    children: React.ReactNode;
    params: { lang: Language };
}) {
    return (
        <html lang={params.lang}>
            <body>{children}</body>
        </html>
    );
}
