import { access, constants, mkdir, readdir } from 'node:fs/promises'
import { logger } from './logger'

const ROOT_FOLDER = new URL('../..', import.meta.url)

export const POSTS_FOLDER = new URL('./posts/', ROOT_FOLDER)
export const ASSETS_FOLDER = new URL('./build-assets/', ROOT_FOLDER)
export const POSTS_ASSETS_FOLDER = new URL('./posts/', ASSETS_FOLDER)
export const AUTHORS_ASSETS_FOLDER = new URL('./authors/', ASSETS_FOLDER)

export const makeDirectoryIfNotExists = async (path: string) => {
  try {
    await access(path, constants.F_OK | constants.W_OK | constants.R_OK)
  } catch {
    logger.debug(`Creating directory: ${path}`)
    await mkdir(path)
  }
}

export const getPostDirectories = async () => {
  const files = await readdir(POSTS_FOLDER.pathname)
  logger.debug('Found posts:', files)
  return files.filter((file) => file !== '.DS_Store')
}

export const writeOutput = async (items: string[]): Promise<string> => {
  const disclaimer = `/* eslint-disable @stylistic/quote-props */
/*
 This file is auto generated by the asset manager
 Do not edit this file directly
 */

// =============================================================
// Types
// =============================================================

type StaticImageData = {
  src: string
  height: number
  width: number
  blurDataURL?: string
  blurWidth?: number
  blurHeight?: number
}

// =============================================================
// Assets
// =============================================================

`

  return disclaimer + items.join('\n\n') + '\n'
}
