name: Check with Biome

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install
      - name: Check with Biome
        run: pnpm check